#!/bin/bash
if [ $1 = "get" ]; then
	if [ $2 = "network.lan.ipaddr" ]; then
		echo 192.168.1.1
	elif [ $2 = "network.lan.netmask" ]; then
		echo 255.255.255.0
	elif [ $2 = "system.@system[0].hostname" ]; then
		echo localghost
	fi
fi
